---
- name: VyOS streaming build
  hosts: localhost
  vars_files:
    - vars.yml
  connection: local

  pre_tasks:
    - name: Verify prerequisites
      ansible.builtin.assert:
        that:
          - ansible_distribution == "Ubuntu"
          - ansible_python_interpreter is defined
        fail_msg: "This playbook requires a Debian-based system with Python properly configured."

    - name: Create artifacts folder
      ansible.builtin.file:
        path: "{{ artifacts_folder }}"
        state: directory
        mode: '0755'
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
      become: yes

  roles:
    - role: install_apps
    - role: install_packer
    - role: vyos_get_files
    - role: vyos_build_image
    - role: convert_image
      when: convert_images | default(false)
  
  post_tasks:
    - name: Applications installation summary
      ansible.builtin.debug:
        msg: "Applications installed."
      when: install_success is defined and install_success == true

    - name: Packer installation summary
      ansible.builtin.debug:
        msg: "Packer installed successfully."
      when: packer_version is defined

    - name: ISO download summary
      ansible.builtin.debug:
        msg: "VyOS rolling ISO for {{ tag_name }} downloaded and verified."
      when: iso_verified is defined and iso_verified == true

    - name: QCOW2 image build summary
      ansible.builtin.debug:
        msg: "VyOS image built and saved at {{ artifacts_folder }}/{{ images_folder }}/{{ packer_vyos_image }}."
      when: build_success is defined and build_success == true

    - name: Image conversion summary
      ansible.builtin.debug:
        msg: "VyOS image converted to {{ converted_formats | join(', ') }} format(s) successfully."
      when: conversion_success is defined and conversion_success == true