---
- name: Check if HashiCorp Packer is installed
  ansible.builtin.stat:
    path: /usr/local/bin/packer
  register: packer_binary

- name: Check Packer version if installed
  ansible.builtin.command: /usr/local/bin/packer version
  register: packer_version_check
  when: packer_binary.stat.exists
  changed_when: false
  failed_when: false

- name: Remove conflicting Ubuntu packer package
  ansible.builtin.apt:
    name: packer
    state: absent
    purge: yes
  become: yes
  when: not packer_binary.stat.exists or (packer_version_check.stdout is defined and 'v1.3' in packer_version_check.stdout)

- name: Install HashiCorp Packer
  block:
    - name: Get latest Packer version from GitHub
      ansible.builtin.uri:
        url: https://api.github.com/repos/hashicorp/packer/releases/latest
        return_content: yes
      register: packer_latest_release

    - name: Set Packer version variable
      ansible.builtin.set_fact:
        packer_version: "{{ packer_latest_release.json.tag_name | regex_replace('^v', '') }}"

    - name: Download Packer binary
      ansible.builtin.get_url:
        url: "https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_linux_amd64.zip"
        dest: "/tmp/packer_{{ packer_version }}_linux_amd64.zip"
        mode: '0644'

    - name: Install unzip if not present
      ansible.builtin.apt:
        name: unzip
        state: present
      become: yes

    - name: Unzip Packer binary
      ansible.builtin.unarchive:
        src: "/tmp/packer_{{ packer_version }}_linux_amd64.zip"
        dest: /usr/local/bin
        remote_src: yes
        mode: '0755'
      become: yes

    - name: Clean up downloaded zip file
      ansible.builtin.file:
        path: "/tmp/packer_{{ packer_version }}_linux_amd64.zip"
        state: absent

    - name: Verify Packer installation
      ansible.builtin.command: /usr/local/bin/packer version
      register: packer_version_output
      changed_when: false

    - name: Display installed Packer version
      ansible.builtin.debug:
        msg: "Installed Packer version: {{ packer_version_output.stdout }}"
  when: not packer_binary.stat.exists or (packer_version_check.stdout is defined and 'v1.3' in packer_version_check.stdout)
